<Project>
  <Target Name="DropUnusedNativeLibraries" AfterTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)"
        Condition="'%(Extension)' == '.dll' and $([System.String]::Copy('%(Filename)').StartsWith('avdevice'))" />
    </ItemGroup>
  </Target>
  <Target Name="DropUnusedNativeLibrariesFromPublish" BeforeTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)"
        Condition="'%(Extension)' == '.dll' and $([System.String]::Copy('%(Filename)').StartsWith('avdevice'))" />
    </ItemGroup>
  </Target>
</Project>
